global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "zeitpeer"
    static_configs:
      # Update the targets to match where the peer telemetry endpoints are reachable
      - targets:
          - "host.docker.internal:9100"
          #- "peer1:9100"
          #- "peer2:9100"
