node_id = 1
listen_addr = "0.0.0.0:32001"
redis_url = "redis://redis:6379/"
#phc_device = "/dev/ptp0"
telemetry_addr = "0.0.0.0:9100"

[sampling]
interval_ms = 250
window_sec = 30
burst = 1

[filter]
lambda = 0.25
trim_ratio = 0.1
best_quantile = 0.6
min_samples_per_peer = 5

[mode]
observer_only = true
control_enable = false

[[peers]]
id = 1
ip = "127.0.0.1"
port = 32001

#[[peers]]
#id = 2
#ip = "127.0.0.1"
#port = 32002

[[ntp_sources]]
id = 9001
host = "time.google.com"
alias = "ntp-google"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000

[[ntp_sources]]
id = 9002
host = "time.cloudflare.com"
alias = "cloudflare"

[[ntp_sources]]
id = 9002
host = "ntp1.rwth-aachen.de"
alias = "ntp1.rwth-aachen.de"

[[ntp_sources]]
id = 9004
host = "time.facebook.com"
alias = "ntp-facebook"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000

[[ntp_sources]]
id = 9005
host = "time.apple.com"
alias = "ntp-apple"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000

[[ntp_sources]]
id = 9006
host = "time.windows.com"
alias = "ntp-windows"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000

[[ntp_sources]]
id = 9007
host = "pool.ntp.org"
alias = "ntp-pool"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000

[[ntp_sources]]
id = 9008
host = "time.nist.gov"
alias = "ntp-nist"
weight = 0.2
poll_interval_ms = 2000
timeout_ms = 1000