version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    restart: unless-stopped

  peer1:
    build: .
    environment:
      - CONFIG=/app/config/peer1.toml
    volumes:
      - ./config:/app/config:ro
    #network_mode: host
    ports:
      - "9100:9100"
    depends_on:
      - redis

#    devices:
#      - "/dev/ptp0:/dev/ptp0"

  peer2:
    build: .
    environment:
      - CONFIG=/app/config/peer2.toml
    volumes:
      - ./config:/app/config:ro
    #network_mode: host
    #ports:
    #  - "9100:9100"
    depends_on:
      - redis
#    devices:
#      - "/dev/ptp0:/dev/ptp0"

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'


  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - redis

  localntpserver:
    build:
      context: localntpserver/
      dockerfile: Dockerfile
    ports:
      - "123:123/udp"
    volumes:
      - ntp-state:/var/lib/chrony
    restart: unless-stopped

  publicntpserver:
    build:
      context: publicntpserver/
      dockerfile: Dockerfile
    ports:
      - "1123:123/udp"
    volumes:
      - ntp-public-state:/var/lib/chrony
    restart: unless-stopped

volumes:
  grafana-data:
  redisinsight:
  ntp-state:
  ntp-public-state:
